# service port
auditboxPort: 2806
tempFile: "temp_"
tempFileSuffix: ".ttl"

# graph db location
endpoint: "http://graphdb:7200/"
# repository that want to be used
provRepo: "vasqua"

# rml file for json data
jsonReceiver: "JSONReceiverSAO.rml"

#shacle shapes
shapes: "shapes.ttl"

#Provenance ontology
provenance: "vasqua_model.owl"

ep_plan: "ep-plan.ttl"
sao: "sao.ttl"

#Workflow ontology
workflow:

#logFile properties
logFile: "log4j.properties"

# default graph name
defaultGraph: "http://vasqua.org/provenance/test"
consentGraph: "http://example.org/consent"
rdtGraph: "http://example.org/rdt"
